enumで設定した値の日本語化
yoshitokamizato/go-to-nago pull request #182
Opened 2020-08-21 04:32 UTC by yuukou3333

## 目的
enumで設定した値の日本語化

## やったこと

-  enum_help gemの導入
-  lacales/ja.ymlの設定
-  既存のmodelに設定したenumの設定見直し

## 備考
自分の環境ではなぜか日本語化されずにレビュワーの方（@great084）の環境では日本語化されているので、もし他の方の環境でも日本語化されていたらローカルの問題だと思うので原因が突き止められ次第マージしたいと考えております。

2020-08-28 13:29 UTC, great084 requested changes
@yuukou3333 

確認しました。
・管理者画面が日本語表示されなくなってしまいました（添付の、性別・立場（※立場って日本語も変ですね。元々そうなのかもしれませんが））。管理画面に対するenumの日本語化対応も必要だと思います。
 
![image](https://user-images.githubusercontent.com/36526480/91565510-48377800-e97d-11ea-8d57-fe8b3ce0f29f.png)

・inquiry(問合せ）に関しても、enumが存在するため、対応する日本語定義を入れてほしいです。(wikiのdatabaseの部分に記載しておきました）

2020-08-28 13:30 UTC, rod91 commented
原因なんだったんですか？

2020-08-29 08:12 UTC, yuukou3333 commented on config/locales/ja.yml
> +        will_open: オープン予定
レビューしていただきありがとうございます！
「立場」は迷った挙句、これにしてしまいました。
roleの日本語化って『役割』とそのままでも違和感ないでしょうか？

管理画面とinquiry(問合せ）モデルの対応もさせていただきます！

2020-08-29 08:15 UTC, yuukou3333 commented
@rod91 
原因は、厳密にはわかっていません。予想ですが、プロセスが残っていたのかもしれません。
コンソールの再起動に加え、2度ほどパソコンを再起動したのですが日本語化されず、時間を置いてから再起動したら日本語化されました。（以前も似たようなことがあったのでMacの不具合の可能性もあります）

2020-09-05 02:28 UTC, rod91 commented
これマージしてOK？問い合わせ対応がまだかな？

2020-09-13 07:29 UTC, rod91 commented
まだかいなw

2020-09-13 10:47 UTC, yuukou3333 commented
連絡遅れてしまい申し訳ありません。。。
対応済みです！

2020-09-20 08:34 UTC, great084 requested changes

2020-09-20 08:34 UTC, great084 commented on app/admin/facilities.rb
> +      f.input :type, as: :select, collection:Facility.type_i18n.invert
@yuukou3333 

管理画面のFacility新規登録画面で以下のエラーとなりました。
![image](https://user-images.githubusercontent.com/36526480/93707060-add6e880-fb66-11ea-9c4f-a67ab24cbe28.png)

正しくは、
`f.input :type, as: :select, collection:Facility.types_i18n.invert`
ではないでしょうか？collectionは複数形（`types`）にする。

2020-09-20 08:34 UTC, great084 commented on config/locales/ja.yml
> +        edit_facility: 施設情報の編集
new_facility: 情報掲載依頼
edit_facility: 情報修正依頼

でおねがいします。

2020-09-20 11:54 UTC, yuukou3333 commented on config/locales/ja.yml
> +        edit_facility: 施設情報の編集
承知しました。

2020-10-02 02:21 UTC, great084 commented
@yuukou3333 


ef71e16のコミットで、masterをマージしてますが、developをマージすべきです。
そうでないと、masterとdevelopに差分があった際、内容が先祖還りする可能性があります・・

2020-10-12 14:21 UTC, great084 requested changes
@yuukou3333 

あらためて、本プルリクエストレビューしました。
内容確認お願いします。（修正後に、稼働確認することもお忘れなくお願いします）

①日本語化時に使用するメソッド名が単数形になっており、エラーが発生している。（複数形にすべき）

例えば、
`collection:Facility.status_i18n`という記載がありますが、正しいメソッド名は複数形の`collection:Facility.statuses_i18n`となります。

以下のプログラムに単数形の記載が点在するので、修正して、修正後に正しく選択リストおよびenum によって日本語化した文言が表示されるか確認をお願いします。（ソースコードの該当箇所にコメント入れていますが漏れがあるかもしれませんの、確認お願いします）

対象
```
app/admin/facilities.rb
app/admin/users.rb
app/admin/inquiries.rb
```

②コンフリクト解消のためのマージ元ブランチについて
ef71e16のコミットで、masterをマージしてますが、正しくはプルリクのマージ先であるdevelopをマージすべきです。
仮にmasterとdevelopに差分があった際、内容が先祖還りする可能性があります・・
今一度developブランチからのマージをお願いします。

2020-10-12 14:21 UTC, great084 commented on app/admin/facilities.rb
> +      f.input :status, as: :select, collection:Facility.status_i18n.invert
method名は複数形の`statuses_i18n`とする必要があります。

2020-10-12 14:21 UTC, great084 commented on app/admin/facilities.rb
> +      facility.type_i18n
method名は複数形の`types_i18n`とする必要があります。

2020-10-12 14:21 UTC, great084 commented on app/admin/facilities.rb
> +      facility.status_i18n
method名は複数形の`statuses_i18n`とする必要があります。

2020-10-12 14:21 UTC, great084 commented on app/admin/facilities.rb
> +        facility.type_i18n
複数形にすること

2020-10-12 14:21 UTC, great084 commented on app/admin/facilities.rb
> +        facility.status_i18n
複数形にすること

2020-10-12 14:21 UTC, great084 commented on app/admin/inquiries.rb
> +      inquiry.status_i18n
複数形にすること

2020-10-12 14:21 UTC, great084 commented on app/admin/inquiries.rb
> +      inquiry.kind_i18n
複数形にすること

2020-10-12 14:21 UTC, great084 commented on app/admin/inquiries.rb
> +      input :status, as: :select, collection:Inquiry.status_i18n.invert
複数形にすること

2020-10-12 14:21 UTC, great084 commented on app/admin/inquiries.rb
> +      input :kind, input_html: { disabled: true }, as: :select, collection:Inquiry.kind_i18n.invert
複数形にすること

2020-10-12 14:21 UTC, great084 commented on app/admin/users.rb
> +      f.input :sex, as: :select, collection:User.sex_i18n.invert
複数形にすること

2020-10-12 14:21 UTC, great084 commented on app/admin/users.rb
> +      f.input :role,  as: :select, collection:User.role_i18n.invert
複数形にすること

2020-10-12 14:21 UTC, great084 commented on app/admin/users.rb
> +      user.sex_i18n
複数形にすること

2020-10-12 14:21 UTC, great084 commented on app/admin/users.rb
> +      user.role_i18n
複数形にすること

2020-10-12 14:21 UTC, great084 commented on app/admin/users.rb
> +        user.sex_i18n
複数形にすること

2020-10-12 14:21 UTC, great084 commented on app/admin/users.rb
> +        user.role_i18n
複数形にすること

2020-10-12 14:21 UTC, great084 commented on config/locales/ja.yml
> +        will_open: オープン予定
確認しました！

2020-10-15 13:59 UTC, great084 approved these changes
指摘事項直っていること確認できました！
最新のdevelopからマージもされているようなのでOKだと思います！

2020-10-16 02:40 UTC, yuukou3333 commented
ご確認、ありがとうございます！
マージさせていただきます！

2020-10-16 02:40 UTC, merged