Enhancement/edit/detail view
yoshitokamizato/go-to-nago pull request #225
Opened 2020-09-13 11:55 UTC by nobuosan

## 目的

詳細画面のUI変更
## やったこと

- Ajaxの書き直し（他のページと共通のものを使っており、デザインを変更した場合他ページに影響があるため）
- レスポンシブ対応

## mobile,PCの画像

before | after
---- | ----
<img src="" width="320"/> | <img src="" width="320"/>
![mobile](https://user-images.githubusercontent.com/49609075/93017359-f4769100-f602-11ea-9d2e-dd5d167abf10.png) | ![pc](https://user-images.githubusercontent.com/49609075/93017361-f9d3db80-f602-11ea-84c7-1eaafe6a2bc2.png)

2020-09-14 13:47 UTC, nobuosan commented
メニューのviewを変更しました。
![screencapture-localhost-3000-facilities-5-menus-2020-09-14-22_44_07](https://user-images.githubusercontent.com/49609075/93093909-358ea400-f6dc-11ea-895b-ff74644047aa.png)

2020-09-17 13:10 UTC, MinoruKotegawa reviewed
内容確認致しました。
個人的に「おすすめポイント」のコメントがかなり右寄りになっている印象ですがいかがでしょうか。

![スクリーンショット 2020-09-17 22 08 19](https://user-images.githubusercontent.com/61322479/93474494-61a36280-f932-11ea-82c5-6f9d453a5f0e.png)

2020-09-17 13:10 UTC, MinoruKotegawa reviewed
内容確認致しました。
個人的に「おすすめポイント」のコメントがかなり右寄りになっている印象ですがいかがでしょうか。

![スクリーンショット 2020-09-17 22 08 19](https://user-images.githubusercontent.com/61322479/93474494-61a36280-f932-11ea-82c5-6f9d453a5f0e.png)

2020-09-17 23:59 UTC, great084 requested changes
トップ画像のお気にいりボタンが画像から、はみ出しています。
また、お気にいりの、カウント数が表示されていません。

![image](https://user-images.githubusercontent.com/36526480/93539901-03f03400-f98d-11ea-9f68-304953ca419d.png)

2020-09-19 10:42 UTC, nobuosan commented
> トップ画像のお気にいりボタンが画像から、はみ出しています。
> 
> また、お気にいりの、カウント数が表示されていません。
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/36526480/93539901-03f03400-f98d-11ea-9f68-304953ca419d.png)

ありがとうございます！
こちら、画像サイズの影響が大きそうですが、
・画像サイズを統一後変更したほうがいいでしょうか？

2020-09-19 23:24 UTC, great084 commented
> こちら、画像サイズの影響が大きそうですが、
> ・画像サイズを統一後変更したほうがいいでしょうか？

そうですね。登録画像のサイズを統一するのであれば、その後でも良いと思います。

ちなみに、画像アップロード時に、carrierwaveで400☓300のサムネイル作るようにしたので、グリッド表示のメニュー一覧画面とかは、こちらを使うと高さそろいます。

2020-09-23 02:56 UTC, merged