マイページ・会員周りのデザイン
yoshitokamizato/go-to-nago pull request #253
Opened 2020-10-01 02:54 UTC by yuukou3333

## 目的
マイページ、会員周りのデザイン

## やったこと
●マイページのデザイン
- タブの作成
- その度調整

●会員周りデザイン（途中）
- ボタンのデザイン変更

## 変更前後の画像
●マイページのデザイン
![image](https://user-images.githubusercontent.com/50189698/94759974-4c234380-03dc-11eb-8041-d05313d75d76.png)

- 色やボタンなどはひろみちさんの作ってくれた、scssを利用しました。
- タブは若干シャドウをつけて浮いてる感じにして、簡単なアニメーションをつけました。

<img src="" width="320"/> | <img src="" width="320"/>

2020-10-01 13:54 UTC, rod91 commented
タブは画面全幅にしてくれますか？

2020-10-18 02:35 UTC, rod91 requested changes
みました！
こちら直ってないですね、タブの外側にマージン、タブの中にも余白がありますね。
タブを全幅にしておき入りの施設の一覧が潰れないようにしてください。

![image](https://user-images.githubusercontent.com/9865774/96357278-d4238000-1134-11eb-84ad-338632ed7b7c.png)

プロフィール部分が仕様と大分違います。
左寄せとテキストのサイズも併せてほしいです。
あと、プロフィールの文字数が最大の時はどうなるか見せてください。

![image](https://user-images.githubusercontent.com/9865774/96357323-43996f80-1135-11eb-85c6-cbf364a87880.png)

お気に入りがなにもない場合にタブのなかが真っ白になってしまいます。
お気に入り情報が無いことを分かるようにして下さい。
あと、もっと見るボタンの挙動がみたいので、Deploy環境にはデータを多めに入れておいてください。

![image](https://user-images.githubusercontent.com/9865774/96357337-85c2b100-1135-11eb-94ac-74fa29d07ac1.png)

編集ボタンをおしたあとのページにデザインが当たっていないので修正お願いします。

![image](https://user-images.githubusercontent.com/9865774/96357358-cfab9700-1135-11eb-8b7d-041c488efd8b.png)

マイページのTOPしかデザインが当たってないみたいです。

![image](https://user-images.githubusercontent.com/9865774/96357365-db975900-1135-11eb-8acb-16f9ac827fe0.png)

2020-10-18 10:37 UTC, yuukou3333 commented
レビューしていただきありがとうございます。
ご指摘いただいた箇所について修正します！

2020-10-22 06:35 UTC, great084 commented
@rod91 @yuukou3333 
先日ゆーこうさんと分担を確認して、このプルリクでは「マイページ」（modal含む）のデザイン適用のみを対象となりました。
他の会員周りのデザインは別プルリクエストで大橋が対応します。

2020-10-23 03:42 UTC, great084 commented
@yuukou3333 

指摘の改善方法について一部補足します。

> こちら直ってないですね、タブの外側にマージン、タブの中にも余白がありますね。
> タブを全幅にしておき入りの施設の一覧が潰れないようにしてください。

topやグルメ・観光スポット一覧では以下のhtml構成となっていますので、参考にしてみてください。
`row`+`col-xx`クラスを繰り返しを使うことで、余白を抑えた全福表示を実現しています。

```
<div class="container-fluid">    ← applicaiton.htmlで記載し全画面適用されているので、個別画面で記載不要

<div class="list-body row">   ← rowクラスを定義
  <div class="list-title underline-blue">
  タイトルエリア
  </div>
  <div class="list-wrapper col-12">   ← col-12クラスを定義し全福設定
    <div class="row " id="facility_lists">  ← 再度rowクラスを定義
      <%= render partial: 'facilities/facilities_list', collection: @facilities, as: 'facility' %> ←render先でcol-xxを定義
・・・

```

> あと、もっと見るボタンの挙動がみたいので、Deploy環境にはデータを多めに入れておいてください。

こちらは、施設情報をimportする際に、いつも使う`facility_data.csv`に変えて、`facility_data_test.csv`を使用すると、大量データが登録されもっと見るボタンの表示確認もできます。

2020-11-29 06:10 UTC, great084 commented
直近のdevelopをマージするとともに、プロフィールおよびお気に入りの表示レイアウトを整えました。

![screencapture-localhost-3000-user-2020-11-29-15_09_31](https://user-images.githubusercontent.com/36526480/100534692-fd1b5280-3254-11eb-8489-247672dce6bf.png)

2020-11-29 10:16 UTC, rod91 approved these changes
ローカルでみていないのですがOKっぽいです。
本番へ入れましょう！

2020-11-30 12:24 UTC, merged