画面の調整（運営会社情報ページ) #215
yoshitokamizato/go-to-nago pull request #257
Opened 2020-10-06 13:15 UTC by MinoruKotegawa

## 目的

「画面の調整（運営会社情報ページ) #215」の修正

## やったこと

- 運営会社情報ページのレイアウトを施設情報ページのレイアウトに合わせる。

## 影響範囲
運営会社情報ページ

## 変更前後の画像

before | after
---- | ----
<img src="" width="320"/> | <img src="" width="320"/>
![スクリーンショット 2020-10-06 22 04 32](https://user-images.githubusercontent.com/61322479/95206264-72ecda00-0821-11eb-9fa5-8b1088a3dcd3.png)|
![スクリーンショット 2020-10-06 22 09 32](https://user-images.githubusercontent.com/61322479/95206286-7a13e800-0821-11eb-8b6c-c71e2c9d0a30.png)

## その他
運営会社情報内容はかみざとさんに提示依頼中。
内容が提示され次第、運営会社情報の内容を更新する。

2020-10-07 13:51 UTC, great084 reviewed
あと、横に間延びした感じがするので、fixpage系は最大幅を狭めてはどうでしょうか？
（久保田さんと相談してほしいです）

2020-10-07 13:51 UTC, great084 commented on app/views/fixedpages/company.html.erb
>      <h3>運営会社情報</h3>
ページの見出しはh1タグに変更をお願いします。
( `.list-little h1`に対するスタイルはcommon.scssで適用済み)

2020-10-10 13:08 UTC, rod91 commented
そうですね、ひろみちさんの仰る通りTOP下のページは全体的に700幅くらいに統一したほうが良いですね。
運営会社ページから更に逸脱してしまうのですが、利用規約やプラポリも併せたいです。

2020-10-10 22:17 UTC, MinoruKotegawa commented
@rod91 @great084 
ご指摘頂きありがとうございます。

指摘内容の修正を行いました事を報告致します。

## 変更前後の画像
<!-- UIの変更前後の画像を入れる（UIに変更があった場合） -->
before | after
---- | ----
<img src="https://user-images.githubusercontent.com/61322479/95666054-1119d080-0b91-11eb-9ee9-63ab17a7f8d7.png" width="320"/> | <img src="https://user-images.githubusercontent.com/61322479/95666072-5211e500-0b91-11eb-97a6-e29766d24b6e.png" width="320"/>
<img src="https://user-images.githubusercontent.com/61322479/95666084-75d52b00-0b91-11eb-8647-eaa64f5a5564.png" width="320"/> | <img src="https://user-images.githubusercontent.com/61322479/95666087-7a99df00-0b91-11eb-912c-5099584fc052.png" width="320"/>
<img src="https://user-images.githubusercontent.com/61322479/95666093-8b4a5500-0b91-11eb-8e59-6cfeb99e2bec.png" width="320"/> | <img src="https://user-images.githubusercontent.com/61322479/95666095-900f0900-0b91-11eb-9c0d-92a715c5acc6.png" width="320"/>
<img src="https://user-images.githubusercontent.com/61322479/95666108-a7e68d00-0b91-11eb-8da1-6af0c576db07.png" width="320"/> | <img src="https://user-images.githubusercontent.com/61322479/95666122-be8ce400-0b91-11eb-801b-0819f4d7c3b8.png" width="320"/>

2020-10-11 03:17 UTC, rod91 requested changes
ありがとうございます！
見た目自体は良いと思います。

ただすみません、張り付けたスタイルは参考にしてほしいという意味だったので、そのままinquiry-areaだと問合せエリアという意味になってしまいます。
別クラスにするか、共通クラスを定義したほうが良いです。

あと、利用規約の最後の「以上」だけはみ出てるのは気になりますw

2020-10-11 12:06 UTC, MinoruKotegawa commented
@rod91 
ご指摘頂きありがとうございます。
指摘内容の修正を行いました。

利用規約末尾の「以上」も左側に寄せました。

![スクリーンショット 2020-10-11 21 03 31](https://user-images.githubusercontent.com/61322479/95678135-a0f96200-0c05-11eb-950e-3c3b01339830.png)

以上です。宜しくお願い致します。

2020-10-11 12:37 UTC, rod91 approved these changes
ありがとうございます！
OKです！

2020-10-11 12:39 UTC, merged