管理画面の絞込項目の修正 #297
yoshitokamizato/go-to-nago pull request #303
Opened 2020-12-10 11:12 UTC by MinoruKotegawa

## 目的

管理画面の絞込項目の修正 #297

## やったこと

- 管理者画面の絞り込みメニューの修正(全般)
- 管理者画面の表示不要な項目の削除(管理者、問い合わせ、ユーザー)

## 変更前後の画像

before | after
---- | ----
<img src="https://user-images.githubusercontent.com/61322479/101763720-84ed4080-3b22-11eb-8c53-983a21187eaf.png" width="320"/> | <img src="https://user-images.githubusercontent.com/61322479/101763730-89b1f480-3b22-11eb-9496-363da09999ef.png" width="320"/>
<img src="https://user-images.githubusercontent.com/61322479/101763884-b960fc80-3b22-11eb-83d1-e08298295c87.png" width="320"/> | <img src="https://user-images.githubusercontent.com/61322479/101763887-bb2ac000-3b22-11eb-8938-402f9d2b889a.png" width="320"/>
<img src="https://user-images.githubusercontent.com/61322479/101763935-cf6ebd00-3b22-11eb-994c-b2e812345360.png" width="320"/> | <img src="https://user-images.githubusercontent.com/61322479/101763951-d3024400-3b22-11eb-8ca8-251fc0095fca.png" width="320"/>
<img src="https://user-images.githubusercontent.com/61322479/101764046-f200d600-3b22-11eb-9e22-eb305fc8377e.png" width="320"/> | <img src="https://user-images.githubusercontent.com/61322479/101764053-f3ca9980-3b22-11eb-9f68-1f2d98b5ac35.png" width="320"/>

## 懸念点
検索条件にenum値を反映させようと試みていますが、絞り込みが上手くいかなくなります。

(例)
問い合わせの「ステータス」に「1(進行中)」を入力して絞り込みを実施。➡︎検索条件が反映される。

inquiries.rb
```
filter :status
```

問い合わせの「ステータス」にenum値を反映させ、「進行中」を選択して絞り込みを実施。➡︎検索条件が反映されず、未実施の内容が表示される。(未実施の内容のみ表示され、進行中の内容が表示されなくなる。)

inquiries.rb
```
filter :status, as: :select, collection:Inquiry.statuses_i18n.invert
```

上記現象については調査中です。
enum値での絞り込みも正常動作できるようになりましたら反映致します。

2020-12-10 14:10 UTC, MinoruKotegawa commented
@rod91 @great084 @nobuosan 
懸念点が解消致しました。
enumを2次元配列にしないと正確に表示及び値渡しが出来ない様です。

[NG]
```
status: { not_started: 0, in_progress: 1, done: 9 }
```

[OK]
```
status: [[:not_started, 0], [:in_progress, 1], [:done, 9]]
```
ActiveAdminのfilterで使用する場合のみ、enum値を上記2次元配列に変換する対応を行いました。

また、ユーザー追加の際にstatus(登録状況)の項目も登録・変更出来る様に修正致しました。

2020-12-10 14:52 UTC, great084 requested changes
@MinoruKotegawa 
確認しました。

①まず、Slackで記載していたenum指定時の検索の件です。

> 問い合わせの「ステータス」にenum値を反映させ、「進行中」を選択して絞り込みを実施。➡︎検索条件が反映されず、未実施の内容が表示される。(未実施の内容のみ表示され、進行中の内容が表示されなくなる。)
> filter :status, as: :select, collection:Inquiry.statuses_i18n.invert
 
原因はactiveadminの検索にはransack gemを使用しているのですが、ransackがうまくenumに対応できていないということです。以下のように変更すると正しく動きます。

`filter :status, as: :select, collection: Inquiry.statuses_i18n.invert.map{ |k, v| [k, Inquiry.statuses[v]]}` 

【原因詳細】
> filter :status, as: :select, collection:Inquiry.statuses_i18n.invert
上記フィルターを指定した際に、サーバへ送付されるパラメータは以下のようになります。

```
{"q"=>{"status_eq"=>"in_progress"}, "commit"=>"絞り込む", "order"=>"id_desc"}
```
これを受けて、本来は、`in_prgress`に対応した`1`で検索をしてほしいのですが、実際のSQLを見ると以下のように`'status'=0`となっています。
```
SELECT COUNT(*) FROM (SELECT 1 AS one FROM `inquiries` WHERE `inquiries`.`status` = 0 LIMIT 30 OFFSET 0) subquery_for_count
```
つまりransack側で`in_progress` → `1`という変換を期待してたのですが、enumの値をとってくれず、数値にカラムに文字列を指定したので、0が指定された。


【解決方法】
filterに指定した`collection:`以降の部分は、コンソールで叩くと以下のようになります。
```
> Inquiry.statuses_i18n.invert
{"未着手"=>"not_started", "進行中"=>"in_progress", "完了"=>"done"}
```
collectionではkeyが表示内容、valueがサーバへ送信される値なので、ハッシュを以下のような形にできれば、ransackで正しく検索できるはずです。
{"未着手"=>0, "進行中"=>1, "完了"=>9}

そのため、collectionに読み込ませる値を以下のようにすると、ransackでも読み取れる値にできます（arrayでもcollectionは問題なく読み込んでくれる模様）
```
Inquiry.statuses_i18n.invert.map{ |key, value| [key, Inquiry.statuses[value]]}
> [["未着手", 0], ["進行中", 1], ["完了", 9]]
```

②また、全体的に一覧画面で全項目を表示しているため見づらくなっているため、項目を絞ったほうが良いと思います。。
（特に「施設・お店」「ユーザ」）

また、検索項目も全項目追加していますが、使うであろう項目に絞ったほうが良いと思います。

あと、問い合わせに関しては削除している項目に関してコードにコメントを入れています。

③ユーザ一覧/詳細でプロフィール画像が、ファイルパスになっているので、サムネイルを表示してほしいです。

2020-12-12 01:17 UTC, MinoruKotegawa commented
@rod91 @great084 
コメントありがとうございます。
現在指摘内容を修正中です。

並行して管理画面一覧から非表示にする項目の検討を行っております。
私の検討内容を記載致しますので、コメント頂けたらと思います。

[ユーザー]
基本的にどれも残しても良い認識。
(強いて言うなら「自己紹介」が非表示になる？)
プロフィール画像はサムネイル表示する様に対応。

[問い合わせ]
ユーザーID
施設ID
お問い合わせ内容が非表示候補。

[施設・お店]
緯度
経度
那覇空港からの所要時間(車)
予算
紹介文
楽しむためのワンポイント・アドバイス
HP情報
Instagram
Youtube
Twitter
作成者ID
更新者IDが非表示候補。
「facility_images」「menu」も日本語化したい。

[メニュー]
料金
メニューの紹介が非表示候補。

[施設画像]
特になし

[管理者]
特になし	

以上です。宜しくお願い致します。

2020-12-12 04:32 UTC, MinoruKotegawa commented
@rod91 @great084 
指摘内容の修正を行いました。

## やったこと
<!-- 実装の技術的な内容を箇条書きで -->
- ひろみちさん指摘内容の修正
- 管理者画面一覧及び絞り込みの項目の選別(復活しやすい様にコメントアウトで対応)
- 施設・お店の「facility_images」「menu」の日本語化
- ユーザーのプロフィール画像のサムネイル表示
- メニュー画面の絞り込み条件の追加
- ユーザー - お住まいの絞り込み条件をenumで選択する対応

## 変更後の画像
![スクリーンショット 2020-12-12 13 27 33](https://user-images.githubusercontent.com/61322479/101975231-4cfb1000-3c7e-11eb-8c51-1be938621d2a.png)
![スクリーンショット 2020-12-12 13 27 42](https://user-images.githubusercontent.com/61322479/101975233-4e2c3d00-3c7e-11eb-991f-bff3c33788a9.png)
![スクリーンショット 2020-12-12 13 27 53](https://user-images.githubusercontent.com/61322479/101975234-4f5d6a00-3c7e-11eb-9c4c-6a449f3ea0c0.png)
![スクリーンショット 2020-12-12 13 28 30](https://user-images.githubusercontent.com/61322479/101975235-508e9700-3c7e-11eb-9b41-5ab045c27035.png)
![スクリーンショット 2020-12-12 13 30 51](https://user-images.githubusercontent.com/61322479/101975237-52f0f100-3c7e-11eb-9b3d-97c48586bef3.png)
![スクリーンショット 2020-12-12 13 30 58](https://user-images.githubusercontent.com/61322479/101975238-54221e00-3c7e-11eb-923e-723f3e4e9311.png)

2020-12-12 09:59 UTC, great084 commented
@MinoruKotegawa 
確認しました！

- enum指定時の検索
→ バッチリ動きますね。OKです。

- 一覧画面の項目
店舗に関してはわたしのPC（横幅1280px）では右側の検索パネルが表示できていないので、
郵便番号、住所、電話番号、定休日、駐車場、開店時間あたりを削ってはいかがでしょうか？

他のモデルは大丈夫だと思います。

- ユーザ一覧/詳細のプロフィール画像
→ OKです。

2020-12-12 13:26 UTC, rod91 commented
問合せ内容は一覧でみたい気もしますけど、とりあえずOKでしょう！

2020-12-12 15:09 UTC, merged